amazon:
  id: 1337-1337-1337
  key: LOREMIPSUMSDOLOR
  secret: TE9SRU1JUFNVTVNET0xPUg==
  associate: yomama-21
  endPoint: "ecs.amazonaws.de"
twitter:
  consumerKey: "LOREMIPSUMS"
  consumerSecret: "LOREMIPSUMSDOLOR"
mongo:
  uri: 'mongodb://localhost/atric'
baseURL: 'http://127.0.0.1:3000'
environment: 'development'