// Generated by CoffeeScript 1.6.2
(function() {
  var argv, books, colors, optimist, retrieve, yaml;

  colors = require('colors');

  optimist = require('optimist').usage('Amazon Trade In Price Check').alias('o', 'out').describe('o', 'Write data to JSON file. Usage: "-o data.json"').alias('t', 'table').describe('t', "Output results as CLI table. Can take comma-separated list of options (currently just 'nonEmpty').").describe('skipBelow', "Don't show entries with a value below that number (in cents).").alias('s', 'web').describe('s', 'Start web server. Optional: --web=PORT (default port is 3000)');

  argv = optimist.argv;

  yaml = require('js-yaml');

  books = require("" + __dirname + "/books.yml");

  retrieve = require("" + __dirname + "/src/retrieve");

  (function() {
    var doImport, fs, i, importer, options, out, output, port, server, table, web, _i, _len, _ref;

    if (argv.h || argv.help) {
      return optimist.showHelp();
    }
    console.log(("Using books.yml with " + books.books.length + " ISBNs").grey);
    table = argv.t || argv.table;
    if (table) {
      options = {};
      if (typeof table === "string") {
        _ref = typeof table.split === "function" ? table.split(',') : void 0;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          options[i] = 1;
        }
      }
      options.skipBelow = argv.skipBelow;
      output = require("" + __dirname + "/src/tableOutput");
      output(retrieve(books.books), options);
    }
    out = argv.o || argv.out;
    if (out) {
      if (typeof out !== "string") {
        console.log("You need to specify a filename.".red);
        return process.exit(1);
      }
      fs = require('fs');
      retrieve(books.books).then(function(data) {
        return fs.writeFile(out, JSON.stringify(data, null, 2), function(err) {
          if (err) {
            console.log(("Error writing file " + out + ": " + err).red);
            return process.exit(1);
          }
          return console.log(("Wrote data to " + out).green);
        });
      });
    }
    web = argv.s || argv.web;
    if (web) {
      port = parseInt(web, 10) || 3000;
      server = require("" + __dirname + "/src/web.coffee");
      server(port, books.books);
    }
    doImport = argv.i || argv["import"];
    if (doImport) {
      console.log("Running import".green);
      importer = require("" + __dirname + "/src/import");
      return importer(books.books);
    }
  })();

}).call(this);
